const fs = require('fs');
const path = require('path');

// Path ke file
const envPath = path.join(__dirname, '.env');
const targetPath = path.join(__dirname, 'src', 'environments', 'environment.ts');
const targetProdPath = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');

try {
    // Baca .env
    const envData = fs.readFileSync(envPath, 'utf8');
    const lines = envData.split('\n');
    const env = {};

    lines.forEach(line => {
        const parts = line.split('=');
        if (parts.length >= 2) {
            const key = parts[0].trim();
            const value = parts.slice(1).join('=').trim();
            if (key && value) env[key] = value;
        }
    });

    const baseUrl = env.BASE_URL || 'http://localhost:8001';

    // Template untuk environment.ts
    const content = `// This file was auto-generated by sync-env.js
export const environment = {
  production: false,
  apiUrl: '${baseUrl}/api',
  storageUrl: '${baseUrl}/storage'
};
`;

    const prodContent = `// This file was auto-generated by sync-env.js
export const environment = {
  production: true,
  apiUrl: '${baseUrl}/api',
  storageUrl: '${baseUrl}/storage'
};
`;

    // Tulis file
    fs.writeFileSync(targetPath, content);
    fs.writeFileSync(targetProdPath, prodContent);

    console.log('✅ Success: environment.ts has been updated to use ' + baseUrl);
} catch (err) {
    console.error('❌ Error syncing environment:', err.message);
}
