// This file was auto-generated by sync-env.js
export const environment = {
  production: true,
  apiUrl: 'https://zeven.api.kelompok27.com/api',
  storageUrl: 'https://zeven.api.kelompok27.com/storage'
};
